# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2023 Sanskar Bhushan <sbdtu5498@gmail.com>
#
# Copyright (C) 2023 Collabora Limited
# Author: Jeny Sadadia <jeny.sadadia@collabora.com>

apiVersion: batch/v1
kind: Job
metadata:
  name: pipeline-github-cloning-job
spec:
  template:
    spec:
      containers:
        - name: pipeline-github-cloning-container
          image: alpine/git
          command: ["git", "clone", "https://github.com/kernelci/kernelci-pipeline.git", "/home/kernelci-pipeline"]
          volumeMounts:
            - name: github-repo
              mountPath: /home/kernelci-pipeline
      restartPolicy: Never
      volumes:
        - name: github-repo
          hostPath:
            path: /home/docker/kernelci-pipeline
            type: DirectoryOrCreate
  backoffLimit: 0
  activeDeadlineSeconds: 60
