---
# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2023 Collabora Limited
# Author: Guillaume Tucker <guillaume.tucker@collabora.com>

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lava-callback
  namespace: kernelci-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lava-callback
  template:
    metadata:
      labels:
        app: lava-callback
    spec:
      containers:
        - name: lava-callback
          image: kernelci/pipeline-lava-callback
          imagePullPolicy: Always
          command:
            - python3
            - src/lava_callback.py
            - --yaml-config=/config/pipeline.yaml
          env:
            - name: KCI_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kernelci-api-token
                  key: token
---
apiVersion: v1
kind: Service
metadata:
  name: lava-callback
  namespace: kernelci-pipeline
spec:
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: lava-callback
