---
# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2023 Collabora Limited
# Author: Guillaume Tucker <guillaume.tucker@collabora.com>

apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-lava
  namespace: kernelci-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-lava
  template:
    metadata:
      labels:
        app: scheduler-lava
    spec:
      containers:
        - name: scheduler
          image: kernelci/kernelci:pipeline@sha256:bb01424c4dedcd2ffa87cef225b09116cf874bc2b91fc63ed6d993d6fc5c43cb
          imagePullPolicy: Always
          command:
            - ./src/scheduler.py
            - --settings=/secrets/kernelci.toml
            - --yaml-config=/config
            - loop
            - --runtimes
            - lava-collabora
            - lava-broonie
            - lava-baylibre
          env:
            - name: KCI_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kernelci-api-token
                  key: token
            - name: KCI_INSTANCE
              value: prod
            - name: KCI_INSTANCE_CALLBACK
              value: https://kernelci-pipeline.westus3.cloudapp.azure.com
          volumeMounts:
            - name: secrets
              mountPath: /secrets
            - name: config-volume
              mountPath: /config
      volumes:
        - name: secrets
          secret:
            secretName: pipeline-secrets
        - name: config-volume
          configMap:
            name: pipeline-configmap
