---
# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2023 Collabora Limited
# Author: Guillaume Tucker <guillaume.tucker@collabora.com>

apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-lava
  namespace: kernelci-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-lava
  template:
    metadata:
      labels:
        app: scheduler-lava
    spec:
      containers:
        - name: scheduler
          image: kernelci/pipeline:latest
          imagePullPolicy: Always
          command:
            - ./src/scheduler.py
            - --settings=/secrets/kernelci.toml
            - --yaml-config=/config/pipeline.yaml
            - loop
            - --runtimes=lava-collabora-early-access
          env:
            - name: KCI_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kernelci-api-token
                  key: token
          volumeMounts:
            - name: secrets
              mountPath: /secrets
            - name: config-volume
              mountPath: /config
      volumes:
        - name: secrets
          secret:
            secretName: pipeline-secrets
        - name: config-volume
          configMap:
            name: pipeline-configmap
