---
# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2023 Collabora Limited
# Author: Guillaume Tucker <guillaume.tucker@collabora.com>

apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-k8s
  namespace: kernelci-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-k8s
  template:
    metadata:
      labels:
        app: scheduler-k8s
    spec:
      containers:
        - name: scheduler
          image: kernelci/kernelci:pipeline@sha256:bb01424c4dedcd2ffa87cef225b09116cf874bc2b91fc63ed6d993d6fc5c43cb
          imagePullPolicy: Always
          command:
            - ./src/scheduler.py
            - --settings=/secrets/kernelci.toml
            - --yaml-config=/config
            - loop
            - --runtimes
            - k8s-gke-eu-west4
            - k8s-all
          env:
            - name: KCI_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kernelci-api-token
                  key: token
          volumeMounts:
            - name: secrets
              mountPath: /secrets
            - name: config-volume
              mountPath: /config
            - name: tmpsecrets
              mountPath: /home/kernelci/secrets
            - name: tmpsecrets
              mountPath: /home/kernelci/.kube
              subPath: k8s-credentials/.kube
            - name: tmpsecrets
              mountPath: /home/kernelci/.config/gcloud
              subPath: k8s-credentials/.config/gcloud
            - name: tmpsecrets
              mountPath: /home/kernelci/.azure
              subPath: k8s-credentials/.azure
      initContainers:
        - name: credentials
          image: denysfcollabora/pipeline
          imagePullPolicy: Always
          volumeMounts:
            - name: tmpsecrets
              mountPath: /tmp/secrets
            - name: k8scredentials
              mountPath: /tmp/k8s
              readOnly: true
          command:
            - tar
            - xzf
            - /tmp/k8s/k8s-credentials.tgz
            - -C
            - /tmp/secrets
      volumes:
        - name: secrets
          secret:
            secretName: pipeline-secrets
        - name: config-volume
          configMap:
            name: pipeline-configmap
        - name: k8scredentials
          secret:
            secretName: k8scredentials
        - name: tmpsecrets
          emptyDir: {}
