---
# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2023 Collabora Limited
# Author: Guillaume Tucker <guillaume.tucker@collabora.com>

apiVersion: apps/v1
kind: Deployment
metadata:
  name: trigger
  namespace: kernelci-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trigger
  template:
    metadata:
      labels:
        app: trigger
    spec:
      containers:
        - name: trigger
          image: kernelci/kernelci:pipeline@sha256:cead9553cf5a0a17015f78e339a514a362d3c7e8753ee6923febf7f446032c52
          imagePullPolicy: Always
          command:
            - ./src/trigger.py
            - --settings=/secrets/kernelci.toml
            - --yaml-config=/config
            - run
            - --trees=!kernelci
            #            - --force
          env:
            - name: KCI_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kernelci-api-token
                  key: token
          volumeMounts:
            - name: secrets
              mountPath: /secrets
            - name: config-volume
              mountPath: /config
      volumes:
        - name: secrets
          secret:
            secretName: pipeline-secrets
        - name: config-volume
          configMap:
            name: pipeline-configmap
