# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2023 Collabora Limited
# Author: Guillaume Tucker <guillaume.tucker@collabora.com>

version: '3'

services:

  kcidb:
    container_name: 'kernelci-pipeline-kcidb'
    build:
      context: 'docker/kcidb'
    env_file: ['.env']
    stop_signal: 'SIGINT'
    networks: ['kcidb']
    command:
      - '/usr/bin/env'
      - 'python3'
      - '/home/kernelci/pipeline/send_kcidb.py'
      - '--settings=${KCI_SETTINGS:-/home/kernelci/config/kernelci.toml}'
      - 'run'
    volumes:
      - './src:/home/kernelci/pipeline'
      - './config:/home/kernelci/config'
      - './data/kcidb:/home/kernelci/data/kcidb'
      - './logs:/home/kernelci/logs'
    restart: on-failure
  postgres:
    container_name: 'kernelci-pipeline-postgres-proxy'
    image: 'gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest'
    command: 'kernelci-production:us-central1:postgresql2 -c/home/kernelci/data/kcidb/kernelci-production-ci-kernelci.json -a0.0.0.0'
    networks: ['kcidb']
    volumes:
      - './data/kcidb:/home/kernelci/data/kcidb'
    restart: on-failure

networks:
  kcidb:
    driver: bridge
