apiVersion: v1
kind: Pod
metadata:
  name: github-cloning-pod
spec:
  containers:
  - name: github-cloning-container
    image: alpine/git
    command: ["git", "clone", "https://github.com/kernelci/kernelci-pipeline.git", "/home/kernelci-pipeline"]
    volumeMounts:
    - name: github-repo
      mountPath: /home/kernelci-pipeline
    # Resource limits needs to be discussed.
    resources:
  volumes:
  - name: github-repo
    hostPath:
      path: /home/docker/kernelci-pipeline

