# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2023 KernelCI Authors.
# Author: Sanskar Bhushan <sbdtu5498@gmail.com>
#
# Copyright (C) 2023 Collabora Limited
# Author: Jeny Sadadia <jeny.sadadia@collabora.com>

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kernelci-pipeline-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kernelci-pipeline-monitor
  template:
    metadata:
      labels:
        app: kernelci-pipeline-monitor
    spec:
      containers:
        - name: kernelci-pipeline-monitor
          image: kernelci/staging-kernelci
          env:
            - name: KCI_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kernelci-pipeline-secrets
                  key: kci-api-token
            - name: SETTINGS
              valueFrom:
                configMapKeyRef:
                  name: kernelci-pipeline-config
                  key: settings
          command:
            - "./pipeline/monitor.py"
            - "--settings=$(SETTINGS)"
            - "run"
          volumeMounts:
            - name: pipeline-volume
              mountPath: /home/kernelci/pipeline
            - name: config-volume
              mountPath: /home/kernelci/config
          resources:
            requests:
              memory: "128M"
              cpu: "250m"
            limits:
              memory: "256M"
              cpu: "500m"
      volumes:
        - name: pipeline-volume
          hostPath:
            path: /home/docker/kernelci-pipeline/src
        - name: config-volume
          hostPath:
            path: /home/docker/kernelci-pipeline/config
