# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2023 KernelCI Authors.
# Author: Sanskar Bhushan <sbdtu5498@gmail.com>

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kernelci-pipeline-notifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kernelci-pipeline-notifier
  template:
    metadata:
      labels:
        app: kernelci-pipeline-notifier
    spec:
      containers:
        - name: kernelci-pipeline-notifier
          image: kernelci/staging-kernelci
          env:
            - name: KCI_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kernelci-pipeline-secrets
                  key: kci-api-token
            - name: SETTINGS
              valueFrom:
                configMapKeyRef:
                  name: kernelci-pipeline-config
                  key: settings
          command:
            - "./pipeline/notifier.py"
            - "--settings=${SETTINGS:-/home/kernelci/config/kernelci.toml}"
            - "run"
          volumeMounts:
            - name: pipeline-volume
              mountPath: /home/kernelci/pipeline
            - name: config-volume
              mountPath: /home/kernelci/config
          # Resource limits needs to be discussed.
          resources:
      volumes:
        - name: pipeline-volume
          hostPath:
            path: /home/docker/kernelci-pipeline/src
        - name: config-volume
          hostPath:
            path: /home/docker/kernelci-pipeline/config
