# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2023 KernelCI Authors.
# Author: Sanskar Bhushan <sbdtu5498@gmail.com>

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kernelci-pipeline-tarball
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kernelci-pipeline-tarball
  template:
    metadata:
      labels:
        app: kernelci-pipeline-tarball
    spec:
      containers:
        - name: kernelci-pipeline-tarball
          image: kernelci/staging-kernelci
          env:
            - name: KCI_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kernelci-pipeline-secrets
                  key: kci-api-token
            - name: SETTINGS
              valueFrom:
                configMapKeyRef:
                  name: kernelci-pipeline-config
                  key: settings
          command:
            - "/home/kernelci/pipeline/tarball.py"
            - "--settings=$(SETTINGS)"
            - "run"
          volumeMounts:
            - name: pipeline-volume
              mountPath: /home/kernelci/pipeline
            - name: config-volume
              mountPath: /home/kernelci/config
            - name: ssh-volume
              mountPath: /home/kernelci/data/ssh
            - name: src-volume
              mountPath: /home/kernelci/data/src
            - name: output-volume
              mountPath: /home/kernelci/data/output
          resources:
            requests:
              memory: "128M"
              cpu: "250m"
            limits:
              memory: "256M"
              cpu: "500m"
      volumes:
        - name: pipeline-volume
          hostPath:
            path: /home/docker/kernelci-pipeline/src
        - name: config-volume
          hostPath:
            path: /home/docker/kernelci-pipeline/config
        - name: ssh-volume
          hostPath:
            path: /home/docker/kernelci-pipeline/data/ssh
        - name: src-volume
          hostPath:
            path: /home/docker/kernelci-pipeline/data/src
        - name: output-volume
          hostPath:
            path: /home/docker/kernelci-pipeline/data/output
