#!/usr/bin/env python3
"""
Validate a JWT generated by jwt_generator.py.
This script uses the tool, generates a unified JWT, then verifies its
signature and claims.
"""

import subprocess
import sys
import tempfile
import time

import jwt

SECRET = "unified-secret"
LEGACY_SECRET = "legacy-secret"
EMAIL = "test@test.com"
SUBJECT = "65265305c74695807499037f"
ORIGIN = "kernelci-pipeline"
LIFETIME_SECONDS = 3600


def generate_token(secret_args):
    result = subprocess.run(
        [
            "python3",
            "tools/jwt_generator.py",
            "--email",
            EMAIL,
            "--subject",
            SUBJECT,
            "--origin",
            ORIGIN,
            "--lifetime-seconds",
            str(LIFETIME_SECONDS),
            *secret_args,
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print("Error generating JWT token:", result.stderr)
        sys.exit(1)
    jwt_token = None
    # iterate over lines
    for line in result.stdout.splitlines():
        if line.startswith("JWT token:"):
            jwt_token = line.strip().split(": ")[1]
            # extract the token from the output
            break
    else:
        print("JWT token not found in output")
        sys.exit(1)

    return jwt_token


def validate_claims(jwt_token, secret):
    before_decode = int(time.time())
    payload = jwt.decode(
        jwt_token,
        secret,
        algorithms=["HS256"],
        audience="fastapi-users:auth",
    )
    after_decode = int(time.time())

    assert payload["sub"] == SUBJECT
    assert payload["email"] == EMAIL
    assert payload["origin"] == ORIGIN
    assert payload["permissions"] == ["checkout", "testretry", "patchset"]
    assert payload["aud"] == ["fastapi-users:auth"]
    assert before_decode <= payload["iat"] <= after_decode
    assert payload["exp"] - payload["iat"] == LIFETIME_SECONDS

    # lava-callback authorizes with permissions rather than an audience.
    pipeline_payload = jwt.decode(
        jwt_token,
        secret,
        algorithms=["HS256"],
        options={"verify_aud": False},
    )
    assert "patchset" in pipeline_payload["permissions"]
    assert pipeline_payload["email"] == EMAIL


def test_explicit_secret():
    jwt_token = generate_token(["--secret", SECRET])
    validate_claims(jwt_token, SECRET)


def test_toml_unified_secret():
    with tempfile.NamedTemporaryFile(mode="w", suffix=".toml") as config:
        config.write(
            f'[jwt]\nsecret = "{LEGACY_SECRET}"\nunified_secret = "{SECRET}"\n'
        )
        config.flush()
        jwt_token = generate_token(["--toml", config.name])

    validate_claims(jwt_token, SECRET)
    try:
        jwt.decode(
            jwt_token,
            LEGACY_SECRET,
            algorithms=["HS256"],
            options={"verify_aud": False},
        )
    except jwt.InvalidSignatureError:
        pass
    else:
        raise AssertionError(
            "Token was signed with legacy rather than unified secret"
        )


def test_pipeline_decode_still_checks_expiration():
    expired_token = jwt.encode(
        {
            "aud": ["fastapi-users:auth"],
            "exp": int(time.time()) - 1,
        },
        SECRET,
        algorithm="HS256",
    )
    try:
        jwt.decode(
            expired_token,
            SECRET,
            algorithms=["HS256"],
            options={"verify_aud": False},
        )
    except jwt.ExpiredSignatureError:
        pass
    else:
        raise AssertionError(
            "Pipeline-compatible decode accepted an expired token"
        )


def main():
    test_explicit_secret()
    test_toml_unified_secret()
    test_pipeline_decode_still_checks_expiration()
    print("Unified JWT generated and validated successfully.")


if __name__ == "__main__":
    main()
