# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2021, 2022 Collabora Limited
# Author: Guillaume Tucker <guillaume.tucker@collabora.com>

FROM kernelci/staging-kernelci
MAINTAINER "KernelCI TSC" <kernelci-tsc@groups.io>

# Install kcidb
RUN pip install git+https://github.com/kernelci/kcidb.git

# Install logspec
RUN pip install git+https://github.com/kernelci/logspec.git@fc48496f93602f6e0029e4c5100e8a2839bf0ea6
