# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2021, 2022 Collabora Limited
# Author: Guillaume Tucker <guillaume.tucker@collabora.com>

FROM kernelci/staging-kernelci
MAINTAINER "KernelCI TSC" <kernelci-tsc@groups.io>

# Install kcidb
RUN pip install git+https://github.com/kernelci/kcidb.git

# Install logspec
RUN pip install git+https://github.com/kernelci/logspec.git@3ca649a4237aaed7ee8be3a8486f53301daeb109
