_anchors:
  kbuild-gcc-14-arm64-chromebook: &kbuild-gcc-14-arm64-chromebook-job
    template: kbuild.jinja2
    kind: kbuild
    image: ghcr.io/kernelci/{image_prefix}gcc-14:arm64-kselftest-kernelci
    params:
      arch: arm64
      compiler: gcc-14
      cross_compile: 'aarch64-linux-gnu-'
      defconfig: defconfig
      fragments:
        - lab-setup
        - arm64-chromebook
        - CONFIG_MODULE_COMPRESS=n
        - CONFIG_MODULE_COMPRESS_NONE=y
    rules: &kbuild-gcc-14-arm64-chromebook-rules
      tree:
        - '!android'
        - '!chromiumos'
        - '!cip'
        - '!media-committers'
        - '!omap'

  baseline: &baseline-job
    template: baseline.jinja2
    kind: job
    kcidb_test_suite: boot
    rules:
      tree:
        - mainline
        - stable-rc
        - stable

  baseline-nfs: &baseline-nfs-job
    template: baseline.jinja2
    kind: job
    params:
      boot_commands: nfs
      rootfs_ref: trixie
    rules:
      tree:
        - mainline
        - stable-rc
        - stable

  kselftest: &kselftest-job
    template: generic.jinja2
    kind: job
    params: &kselftest-params
      test_method: kselftest
      boot_commands: nfs
      rootfs_ref: trixie-kselftest
      job_timeout: 10
    kcidb_test_suite: kselftest
    rules:
      tree:
        - collabora-next:for-kernelci

  fluster-debian: &fluster-debian-job
    template: 'generic.jinja2'
    kind: job
    params: &fluster-debian-params
      test_method: fluster-debian
      boot_commands: nfs
      rootfs_ref: trixie-gst-fluster
      job_timeout: 30
      videodec_parallel_jobs: 1
      videodec_timeout: 90
    rules:
      tree:
        - mainline
        - next

  watchdog-reset: &watchdog-reset-job
    template: generic.jinja2
    kind: job
    params: &watchdog-reset-job-params
      test_method: watchdog-reset
      bl_message: 'coreboot-'
      wdt_dev: 'watchdog0'
    rules:
      tree:
        - mainline
        - stable-rc
        - stable
    kcidb_test_suite: kernelci_watchdog_reset

  wifi-basic: &wifi-basic-job
    template: generic.jinja2
    kind: job
    params: &wifi-basic-job-params
      test_method: wifi-basic
      boot_commands: nfs
      rootfs_ref: trixie-wifi
    rules:
      tree:
        - mainline
        - stable-rc
        - stable
    kcidb_test_suite: kernelci_wifi_basic

jobs:

  baseline-arm64-mediatek-chromebook: *baseline-job
  baseline-arm64-qualcomm-chromebook: *baseline-job
  baseline-nfs-arm64-mediatek-chromebook: *baseline-nfs-job
  baseline-nfs-arm64-qualcomm-chromebook: *baseline-nfs-job
  baseline-nfs-x86-amd-chromebook: *baseline-nfs-job
  baseline-nfs-x86-intel-chromebook: *baseline-nfs-job
  baseline-x86-amd-chromebook: *baseline-job
  baseline-x86-intel-chromebook: *baseline-job

  kbuild-gcc-14-arm64-chromebook: *kbuild-gcc-14-arm64-chromebook-job

  kbuild-gcc-14-arm64-chromebook-media-committers:
    <<: *kbuild-gcc-14-arm64-chromebook-job
    rules:
      tree:
        - 'media-committers'

  kselftest-acpi:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      collections: acpi
    kcidb_test_suite: kselftest.acpi

  kselftest-device-error-logs:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      collections: devices/error_logs
    kcidb_test_suite: kselftest.device_error_logs

  fluster-debian-av1:
    <<: *fluster-debian-job
    params:
      <<: *fluster-debian-params
      testsuite: 'AV1-TEST-VECTORS'
      decoders:
        - 'GStreamer-AV1-V4L2SL-Gst1.0'
    kcidb_test_suite: fluster.debian.v4l2.gstreamer_av1

  fluster-debian-av1-chromium-10bit:
    <<: *fluster-debian-job
    params:
      <<: *fluster-debian-params
      testsuite: 'CHROMIUM-10bit-AV1-TEST-VECTORS'
      decoders:
        - 'GStreamer-AV1-V4L2SL-Gst1.0'
    kcidb_test_suite: fluster.debian.v4l2.gstreamer_av1_chromium

  fluster-debian-h264:
    <<: *fluster-debian-job
    params:
      <<: *fluster-debian-params
      testsuite: 'JVT-AVC_V1'
      decoders:
        - 'GStreamer-H.264-V4L2-Gst1.0'
        - 'GStreamer-H.264-V4L2SL-Gst1.0'
    kcidb_test_suite: fluster.debian.v4l2.gstreamer_h264

  fluster-debian-h264-frext:
    <<: *fluster-debian-job
    params:
      <<: *fluster-debian-params
      testsuite: 'JVT-FR-EXT'
      decoders:
        - 'GStreamer-H.264-V4L2-Gst1.0'
        - 'GStreamer-H.264-V4L2SL-Gst1.0'
    kcidb_test_suite: fluster.debian.v4l2.gstreamer_h264_frext

  fluster-debian-h265:
    <<: *fluster-debian-job
    params:
      <<: *fluster-debian-params
      testsuite: 'JCT-VC-HEVC_V1'
      decoders:
        - 'GStreamer-H.265-V4L2-Gst1.0'
        - 'GStreamer-H.265-V4L2SL-Gst1.0'
    kcidb_test_suite: fluster.debian.v4l2.gstreamer_h265

  fluster-debian-vp8:
    <<: *fluster-debian-job
    params:
      <<: *fluster-debian-params
      testsuite: 'VP8-TEST-VECTORS'
      decoders:
        - 'GStreamer-VP8-V4L2-Gst1.0'
        - 'GStreamer-VP8-V4L2SL-Gst1.0'
    kcidb_test_suite: fluster.debian.v4l2.gstreamer_vp8

  fluster-debian-vp9:
    <<: *fluster-debian-job
    params:
      <<: *fluster-debian-params
      testsuite: 'VP9-TEST-VECTORS'
      decoders:
        - 'GStreamer-VP9-V4L2-Gst1.0'
        - 'GStreamer-VP9-V4L2SL-Gst1.0'
    kcidb_test_suite: fluster.debian.v4l2.gstreamer_vp9

  watchdog-reset-arm64-mediatek: *watchdog-reset-job
  watchdog-reset-arm64-qualcomm: *watchdog-reset-job
  watchdog-reset-x86-amd: *watchdog-reset-job
  watchdog-reset-x86-intel: *watchdog-reset-job

  wifi-basic-arm64-mediatek: *wifi-basic-job
  wifi-basic-x86-amd: *wifi-basic-job
  wifi-basic-x86-intel: *wifi-basic-job
