_anchors:

  kbuild-gcc-10-arm64-chromeos: &kbuild-gcc-10-arm64-chromeos-job
    template: kbuild.jinja2
    kind: kbuild
    image: kernelci/staging-gcc-10:arm64-kselftest-kernelci
    params: &kbuild-gcc-10-arm64-chromeos-params
      arch: arm64
      compiler: gcc-10
      cross_compile: 'aarch64-linux-gnu-'
      cross_compile_compat: 'arm-linux-gnueabihf-'
      defconfig: 'cros://chromeos-{krev}/{arch}/chromiumos-{flavour}.flavour.config'
      flavour: '{arch}-generic'
      fragments:
        - arm64-chromebook
        - CONFIG_MODULE_COMPRESS=n

  kbuild-gcc-10-x86-chromeos: &kbuild-gcc-10-x86-chromeos-job
    <<: *kbuild-gcc-10-arm64-chromeos-job
    image: kernelci/staging-gcc-10:x86-kselftest-kernelci
    params: &kbuild-gcc-10-x86-chromeos-params
      arch: x86_64
      compiler: gcc-10
      defconfig: 'cros://chromeos-{krev}/{arch}/chromeos-{flavour}.flavour.config'
      flavour: '{arch}-generic'
      fragments:
        - x86-board
        - CONFIG_MODULE_COMPRESS=n

  tast: &tast-job
    template: tast.jinja2
    kind: test

  tast-basic: &tast-basic-job
    <<: *tast-job
    params:
      tests:
        - platform.CheckDiskSpace
        - platform.TPMResponsive

  tast-hardware: &tast-hardware-job
    <<: *tast-job
    params:
      tests:
        - graphics.HardwareProbe
        - graphics.KernelConfig
        - graphics.KernelMemory
        - hardware.DiskErrors
        - hardware.SensorAccel
        - hardware.SensorIioservice
        - hardware.SensorIioserviceHard
        - hardware.SensorLight
        - hardware.SensorPresence
        - hardware.SensorActivity
        - health.ProbeSensorInfo
        - health.DiagnosticsRun.*
        - health.ProbeAudioHardwareInfo
        - health.ProbeAudioInfo
        - health.ProbeBacklightInfo
        - health.ProbeCPUInfo
        - health.ProbeFanInfo
        - inputs.PhysicalKeyboardKernelMode

  tast-kernel: &tast-kernel-job
    <<: *tast-job
    params:
      tests:
        - kernel.Bloat
        - kernel.ConfigVerify.chromeos_kernelci
        - kernel.ConfigVerify.chromeos
        - kernel.CPUCgroup
        - kernel.Cpuidle
        - kernel.CryptoAPI
        - kernel.CryptoDigest
        - kernel.ECDeviceNode
        - kernel.HighResTimers
        - kernel.Limits
        - kernel.PerfCallgraph

  tast-mm-misc: &tast-mm-misc-job
    <<: *tast-job
    params:
      tests:
        - camera.Suspend
        - camera.V4L2
        - camera.V4L2Compliance
        - camera.V4L2.certification
        - camera.V4L2.supported_formats
        - graphics.Clvk.api_tests
        - graphics.Clvk.simple_test
        - graphics.DRM.atomic_test_overlay_upscaling
        - graphics.DRM.atomic_test_plane_alpha
        - graphics.DRM.atomic_test_plane_ctm
        - graphics.DRM.atomic_test_primary_pageflip
        - graphics.DRM.atomic_test_rgba_primary
        - graphics.DRM.atomic_test_video_overlay
        - graphics.DRM.atomic_test_video_underlay
        - graphics.DRM.dmabuf_test
        - graphics.DRM.drm_cursor_test
        - graphics.DRM.gbm_test
        - graphics.DRM.linear_bo_test
        - graphics.DRM.mapped_access_perf_test
        - graphics.DRM.mmap_test
        - graphics.DRM.null_platform_test
        - graphics.DRM.swrast_test
        - graphics.DRM.vk_glow
        - graphics.DRM.yuv_to_rgb_test
        - graphics.GLBench
        - security.GPUSandboxed
        - video.ImageProcessor.image_processor_unit_test
        - video.MemCheck.av1_hw
        - video.PlatformVAAPIUnittest

  tast-perf: &tast-perf-job
    <<: *tast-job
    params:
      tests:
        - filemanager.UIPerf.directory_list
        - filemanager.UIPerf.list_apps
        - settings.DeviceMouseScrollAcceleration
        - ui.DesksAnimationPerf
        - ui.DragTabInTabletPerf.touch
        - ui.OverviewWithExpandedDesksBarPerf

  tast-perf-long-duration: &tast-perf-long-duration-job
    <<: *tast-job
    params:
      tests:
        - filemanager.ZipPerf
        - storage.WriteZeroPerf
        - ui.WindowCyclePerf
        - ui.WindowResizePerf
        - ui.BubbleLauncherAnimationPerf
        - ui.DragMaximizedWindowPerf
        - ui.DragTabInClamshellPerf
        - ui.DragTabInTabletPerf

  tast-platform: &tast-platform-job
    <<: *tast-job
    params:
      tests:
        - platform.CheckDiskSpace
        - platform.CheckProcesses
        - platform.CheckTracefsInstances
        - platform.CrosDisks
        - platform.CrosDisksArchive
        - platform.CrosDisksFilesystem
        - platform.CrosDisksFormat
        - platform.CrosDisksRename
        - platform.CrosDisksSSHFS
        - platform.CrosID
        - platform.DeviceHwid
        - platform.DLCService
        - platform.DLCServiceCrosDeploy
        - platform.DLCServicePreloading
        - platform.DMVerity
        - platform.DumpVPDLog
        - platform.Firewall
        - platform.LocalPerfettoTBMTracedProbes
        - platform.Memd
        - platform.Mtpd
        - platform.SerialNumber
        - platform.TPMResponsive
        - platform.TPMStatus
        - storage.HealthInfo
        - storage.InternalStorage
        - storage.LowPowerStateResidence

  tast-power: &tast-power-job
    <<: *tast-job
    params:
      tests:
        - power.CheckStatus
        - power.CpufreqConf
        - power.TabletModePowerOffMenu.close_menu
        - power.TabletModePowerOffMenu.shut_down
        - power.TabletModePowerOffMenu.sign_out
        - power.SmartDim.flatbuffer
        - power.SmartDim
        - power.SmartDim.lacros
        - power.UtilCheck
        - typec.Basic

  tast-sound: &tast-sound-job
    <<: *tast-job
    params:
      tests:
        - audio.AloopLoadedFixture
        - audio.AloopLoadedFixture.stereo
        - audio.ALSAConformance
        - audio.BrowserShellAudioToneCheck
        - audio.CheckingAudioFormats
        - audio.CrasFeatures
        - audio.CrasPlay
        - audio.CrasRecord
        - audio.CrasRecordQuality
        - audio.DevicePlay
        - audio.DevicePlay.unstable_model
        - audio.DevicePlay.unstable_platform
        - audio.DeviceRecord
        - audio.UCMSequences.section_device
        - audio.UCMSequences.section_modifier
        - audio.UCMSequences.section_verb

  tast-ui: &tast-ui-job
    <<: *tast-job
    params:
      tests:
        - ui.DesktopControl
        - ui.HotseatAnimation.non_overflow_shelf
        - ui.HotseatAnimation.non_overflow_shelf_lacros
        - ui.HotseatAnimation.overflow_shelf
        - ui.HotseatAnimation.overflow_shelf_lacros
        - ui.HotseatAnimation.shelf_with_navigation_widget
        - ui.HotseatAnimation.shelf_with_navigation_widget_lacros
        - ui.WindowControl

  tast-video: &tast-video-job
    <<: *tast-job
    params:
      tests:
        - video.ChromeStackDecoder.*

jobs:

  baseline-arm64-chromeos-mediatek: &baseline-job
    template: baseline.jinja2
    kind: test

  baseline-arm64-chromeos-qualcomm: *baseline-job
  baseline-x86-pineview: *baseline-job
  baseline-x86-stoneyridge: *baseline-job
  baseline-x86-stoneyridge-staging: *baseline-job

  kbuild-gcc-10-arm64-chromeos-mediatek:
    <<: *kbuild-gcc-10-arm64-chromeos-job
    params:
      <<: *kbuild-gcc-10-arm64-chromeos-params
      flavour: mediatek

  kbuild-gcc-10-arm64-chromeos-qualcomm:
    <<: *kbuild-gcc-10-arm64-chromeos-job
    params:
      <<: *kbuild-gcc-10-arm64-chromeos-params
      flavour: qualcomm

  kbuild-gcc-10-x86-chromeos-pineview:
    <<: *kbuild-gcc-10-x86-chromeos-job
    params:
      <<: *kbuild-gcc-10-x86-chromeos-params
      flavour: intel-pineview

  kbuild-gcc-10-x86-chromeos-stoneyridge:
    <<: *kbuild-gcc-10-x86-chromeos-job
    params:
      <<: *kbuild-gcc-10-x86-chromeos-params
      flavour: amd-stoneyridge

  tast-basic-arm64-mediatek: *tast-basic-job
  tast-basic-arm64-qualcomm: *tast-basic-job
  tast-basic-x86-pineview: *tast-basic-job
  tast-basic-x86-stoneyridge: *tast-basic-job

  tast-hardware-arm64-mediatek: *tast-hardware-job
  tast-hardware-arm64-qualcomm: *tast-hardware-job
  tast-hardware-x86-pineview: *tast-hardware-job
  tast-hardware-x86-stoneyridge: *tast-hardware-job

  tast-kernel-arm64-mediatek: *tast-kernel-job
  tast-kernel-arm64-qualcomm: *tast-kernel-job
  tast-kernel-x86-pineview: *tast-kernel-job
  tast-kernel-x86-stoneyridge: *tast-kernel-job

  tast-mm-misc-arm64-mediatek: *tast-mm-misc-job
  tast-mm-misc-arm64-qualcomm: *tast-mm-misc-job
  tast-mm-misc-x86-pineview: *tast-mm-misc-job
  tast-mm-misc-x86-stoneyridge: *tast-mm-misc-job

  tast-perf-arm64-mediatek: *tast-perf-job
  tast-perf-arm64-qualcomm: *tast-perf-job
  tast-perf-x86-pineview: *tast-perf-job
  tast-perf-x86-stoneyridge: *tast-perf-job

  tast-perf-long-duration-arm64-mediatek: *tast-perf-long-duration-job
  tast-perf-long-duration-arm64-qualcomm: *tast-perf-long-duration-job
  tast-perf-long-duration-x86-pineview: *tast-perf-long-duration-job
  tast-perf-long-duration-x86-stoneyridge: *tast-perf-long-duration-job

  tast-platform-arm64-mediatek: *tast-platform-job
  tast-platform-arm64-qualcomm: *tast-platform-job
  tast-platform-x86-pineview: *tast-platform-job
  tast-platform-x86-stoneyridge: *tast-platform-job

  tast-power-arm64-mediatek: *tast-power-job
  tast-power-arm64-qualcomm: *tast-power-job
  tast-power-x86-pineview: *tast-power-job
  tast-power-x86-stoneyridge: *tast-power-job

  tast-sound-arm64-mediatek: *tast-sound-job
  tast-sound-arm64-qualcomm: *tast-sound-job
  tast-sound-x86-pineview: *tast-sound-job
  tast-sound-x86-stoneyridge: *tast-sound-job

  tast-ui-arm64-mediatek: *tast-ui-job
  tast-ui-arm64-qualcomm: *tast-ui-job
  tast-ui-x86-pineview: *tast-ui-job
  tast-ui-x86-stoneyridge: *tast-ui-job

  tast-video-arm64-mediatek: *tast-video-job
  tast-video-arm64-qualcomm: *tast-video-job
  tast-video-x86-pineview: *tast-video-job
  tast-video-x86-stoneyridge: *tast-video-job
