_anchors:

  arm64-device: &arm64-device
    arch: arm64
    boot_method: u-boot

  arm-device: &arm-device
    <<: *arm64-device
    arch: arm

  riscv-device: &riscv-device
    arch: riscv
    boot_method: u-boot

  x86_64-device: &x86_64-device
    arch: x86_64
    boot_method: grub
    mach: x86

platforms:
# arm64 platforms
  zynqmp-zcu102:
    <<: *arm64-device
    mach: zynqmp
    dtb: dtbs/xilinx/zynqmp-zcu102-rev1.0.dtb
    compatible: ['xlnx,zynqmp-zcu102-rev1.0', 'xlnx,zynqmp-zcu102', 'xlnx,zynqmp']

  r8a774a1-hihope-rzg2m-ex:
    <<: *arm64-device
    mach: renesas
    dtb: dtbs/renesas/r8a774a1-hihope-rzg2m-ex.dtb
    compatible: ['hoperun,hihope-rzg2-ex', 'hoperun,hihope-rzg2m']

# arm platforms
  de0-nano-soc:
    <<: *arm-device
    mach: intel
    dtb: dtbs/socfpga_cyclone5_de0_nano_soc.dtb
    compatible: ['terasic,de0-atlas', 'altr,socfpga-cyclone5', 'altr,socfpga']

  r8a7743-iwg20d-q7:
    <<: *arm-device
    mach: renesas
    dtb: dtbs/r8a7743-iwg20d-q7-dbcm-ca.dtb
    compatible: ['iwave,g20d', 'iwave,g20m', 'renesas,r8a7743']
