_anchors:

  arm64-chromebook-device: &arm64-chromebook-device
    arch: arm64
    boot_method: depthcharge
    params: &arm64-chromebook-device-params
      flash_kernel:
        url: https://storage.chromeos.kernelci.org/images/kernel/v6.1-{mach}
        image: 'kernel/Image'
      nfsroot: https://storage.chromeos.kernelci.org/images/rootfs/debian/trixie-cros-flash/20240422.0/{debarch}
    rules: &arm64-chromebook-device-rules
      defconfig:
        - '!allnoconfig'
        - '!allmodconfig'
      fragments:
        - 'arm64-chromebook'

  x86-chromebook-device: &x86-chromebook-device
    arch: x86_64
    boot_method: depthcharge
    mach: x86
    params: &x86-chromebook-device-params
      <<: *arm64-chromebook-device-params
      flash_kernel:
        url: https://storage.chromeos.kernelci.org/images/kernel/cros-20230815-amd64/clang-14
        image: 'kernel/bzImage'
    rules: &x86-chromebook-device-rules
      <<: *arm64-chromebook-device-rules
      fragments:
        - 'x86-board'

platforms:
  acer-R721T-grunt:
    <<: *x86-chromebook-device
    params:
      <<: *x86-chromebook-device-params
      short_name: grunt
    rules:
      <<: *x86-chromebook-device-rules
      branch:
        - 'mainline:master'
        - 'next:master'
        - 'stable:linux-5.10.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-5.10.y'
        - 'stable-rc:linux-6.12.y'

  acer-cbv514-1h-34uz-brya:
    <<: *x86-chromebook-device
    params:
      <<: *x86-chromebook-device-params
      short_name: brya
    rules:
      <<: *x86-chromebook-device-rules
      branch:
        - 'mainline:master'
        - 'next:master'
        - 'stable:linux-6.6.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-6.6.y'
        - 'stable-rc:linux-6.12.y'

  acer-chromebox-cxi5-brask:
    <<: *x86-chromebook-device
    params:
      <<: *x86-chromebook-device-params
      short_name: brask
    rules:
      <<: *x86-chromebook-device-rules
      branch:
        - 'mainline:master'
        - 'next:master'
        - 'stable:linux-6.6.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-6.6.y'
        - 'stable-rc:linux-6.12.y'

  acer-cp514-2h-1130g7-volteer: &chromebook-volteer-device
    <<: *x86-chromebook-device
    params:
      <<: *x86-chromebook-device-params
      short_name: volteer
    rules:
      <<: *x86-chromebook-device-rules
      branch:
        - 'mainline:master'
        - 'next:master'
        - 'stable:linux-5.4.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-5.4.y'
        - 'stable-rc:linux-6.12.y'

  acer-cp514-2h-1160g7-volteer: *chromebook-volteer-device

  acer-cp514-3wh-r0qs-guybrush:
    <<: *x86-chromebook-device
    params:
      <<: *x86-chromebook-device-params
      short_name: guybrush
    rules:
      <<: *x86-chromebook-device-rules
      branch:
        - 'mainline:master'
        - 'next:master'
        - 'stable:linux-6.6.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-6.6.y'
        - 'stable-rc:linux-6.12.y'

  asus-CX3402CVA-brya:
    <<: *x86-chromebook-device
    params:
      <<: *x86-chromebook-device-params
      short_name: brya
    rules:
      <<: *x86-chromebook-device-rules
      branch:
        - 'mainline:master'
        - 'next:master'
        - 'stable:linux-6.6.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-6.6.y'
        - 'stable-rc:linux-6.12.y'

  asus-CM1400CXA-dalboz: &chromebook-zork-device
    <<: *x86-chromebook-device
    params:
      <<: *x86-chromebook-device-params
      short_name: zork
    rules:
      <<: *x86-chromebook-device-rules
      branch:
        - 'mainline:master'
        - 'next:master'
        - 'stable:linux-5.4.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-5.4.y'
        - 'stable-rc:linux-6.12.y'

  dell-latitude-3445-7520c-skyrim:
    <<: *x86-chromebook-device
    params:
      <<: *x86-chromebook-device-params
      short_name: skyrim
    rules:
      <<: *x86-chromebook-device-rules
      branch:
        - 'mainline:master'
        - 'next:master'
        - 'stable:linux-6.6.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-6.6.y'
        - 'stable-rc:linux-6.12.y'

  hp-x360-14a-cb0001xx-zork: *chromebook-zork-device
  lenovo-TPad-C13-Yoga-zork: *chromebook-zork-device

  mt8183-kukui-jacuzzi-juniper-sku16: &mediatek-chromebook-device
    <<: *arm64-chromebook-device
    mach: mediatek
    dtb: dtbs/mediatek/mt8183-kukui-jacuzzi-juniper-sku16.dtb
    compatible: ['google,juniper-sku16', 'google,juniper', 'mediatek,mt8183']
    params:
      <<: *arm64-chromebook-device-params
      short_name: jacuzzi
    rules:
      <<: *arm64-chromebook-device-rules
      branch:
        - 'mainline:master'
        - 'next:master'
        - 'stable:linux-6.1.y'
        - 'stable:linux-6.6.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-6.1.y'
        - 'stable-rc:linux-6.6.y'
        - 'stable-rc:linux-6.12.y'

  mt8196-rauru-navi-sku0:
    <<: *mediatek-chromebook-device
    dtb: dtbs/mediatek/mt8196-rauru-navi-sku0.dtb
    compatible: ['google,rauru-navi-sku0', 'mediatek,mt8196']
    params:
      <<: *arm64-chromebook-device-params
      short_name: rauru
    rules:
      <<: *arm64-chromebook-device-rules
      branch:
        - 'mainline:master'
        - 'next:master'

  mt8195-cherry-tomato-r2:
    <<: *mediatek-chromebook-device
    dtb:
      - 'dtbs/mediatek/mt8195-cherry-tomato-r2.dtb'
      - 'dtbs/mediatek/mt8195-tomato-rev2.dtb'
    compatible: ['google,tomato-rev2', 'google,tomato', 'mediatek,mt8195']
    params:
      <<: *arm64-chromebook-device-params
      short_name: cherry-r2
    rules:
      <<: *arm64-chromebook-device-rules
      branch:
        - 'mainline:master'
        - 'next:master'
        - 'stable:linux-6.6.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-6.6.y'
        - 'stable-rc:linux-6.12.y'

  sc7180-trogdor-kingoftown: &trogdor-chromebook-device
    <<: *arm64-chromebook-device
    mach: qcom
    dtb:
      - dtbs/qcom/sc7180-trogdor-kingoftown.dtb
      - dtbs/qcom/sc7180-trogdor-kingoftown-r1.dtb
    compatible: ['google,kingoftown', 'qcom,sc7180']
    params:
      <<: *arm64-chromebook-device-params
      flash_kernel:
        url: https://storage.chromeos.kernelci.org/images/kernel/v6.1-qualcomm
        image: 'kernel/Image'
        dtb: 'dtbs/qcom/sc7180-trogdor-kingoftown-r1.dtb'
      short_name: trogdor
    rules:
      branch:
        - 'mainline:master'
        - 'next:master'
        - 'stable:linux-6.6.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-6.6.y'
        - 'stable-rc:linux-6.12.y'

  sc7180-trogdor-lazor-limozeen:
    <<: *trogdor-chromebook-device
    dtb: dtbs/qcom/sc7180-trogdor-lazor-limozeen-nots-r5.dtb
    compatible: ['google,lazor-rev5-sku5', 'google,lazor-rev5-sku6']

  sc7180-trogdor-wormdingler-rev1-boe:
    <<: *trogdor-chromebook-device
    dtb: dtbs/qcom/sc7180-trogdor-wormdingler-rev1-boe.dtb
    compatible: ['google,wormdingler-sku1024', 'qcom,sc7180']
