# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2021, 2022, 2023 Collabora Limited
# Author: Guillaume Tucker <guillaume.tucker@collabora.com>

# Not directly loaded into the config, only used for YAML aliases in this file
_anchors:

### Device definition templates

  arm64-device: &arm64-device
    arch: arm64
    boot_method: u-boot

  arm-device: &arm-device
    <<: *arm64-device
    arch: arm

  riscv-device: &riscv-device
    arch: riscv
    boot_method: u-boot

  x86_64-device: &x86_64-device
    arch: x86_64
    boot_method: grub
    mach: x86


platforms:

  aaeon-UPN-EHLX4RE-A10-0864: *x86_64-device

  armada-388-clearfog-pro:
    <<: *arm-device
    mach: marvell
    dtb: dtbs/armada-388-clearfog-pro.dtb
    compatible: ['solidrun,clearfog-pro-a1', 'solidrun,clearfog-a1', 'marvell,armada388', 'marvell,armada385', 'marvell,armada380']

  am57xx-beagle-x15:
    <<: *arm-device
    mach: omap
    dtb: dtbs/am57xx-beagle-x15.dtb
    compatible: ['ti,am572x-beagle-x15', 'ti,am5728', 'ti,dra742', 'ti,dra74', 'ti,dra7']

  at91-sama5d4_xplained:
    <<: *arm-device
    mach: microchip
    dtb: dtbs/at91-sama5d4_xplained.dtb
    compatible: ['atmel,sama5d4-xplained', 'atmel,sama5d4', 'atmel,sama5']

  at91sam9g20ek:
    <<: *arm-device
    mach: atmel
    dtb: dtbs/at91sam9g20ek.dtb
    compatible: ['atmel,at91sam9g20ek', 'atmel,at91sam9g20', 'atmel,at91sam9']

  bcm2711-rpi-4-b:
    <<: *arm64-device
    mach: broadcom
    dtb: dtbs/broadcom/bcm2711-rpi-4-b.dtb
    compatible: ['raspberrypi,4-model-b', 'brcm,bcm2711']

  bcm2837-rpi-3-b-plus:
    <<: *arm64-device
    mach: broadcom
    dtb: dtbs/broadcom/bcm2837-rpi-3-b-plus.dtb
    compatible: ['raspberrypi,3-model-b-plus', rbrcm,bcm2837;]

  # No job is being scheduled on these board as its infrastructure errors need to be fixed first.
  bcm2836-rpi-2-b:
    <<: *arm-device
    mach: broadcom
    dtb: dtbs/bcm2836-rpi-2-b.dtb
    compatible: ['raspberrypi,2-model-b', 'brcm,bcm2836']

  beagle-xm:
    <<: *arm-device
    mach: omap
    dtb: dtbs/omap3-beagle-xm.dtb
    compatible: ['ti,omap3-beagle-xm', 'ti,omap3630', 'ti,omap3']

  beaglebone-black:
    <<: *arm-device
    mach: omap
    dtb: dtbs/am335x-boneblack.dtb
    compatible: ['ti,am335x-bone-black', 'ti,am335x-bone', 'ti,am33xx']

  cd8180-orion-o6:
    <<: *arm64-device
    mach: cix
    boot_method: grub

  da850-lcdk:
    <<: *arm-device
    mach: davinci
    dtb: dtbs/da850-lcdk.dtb
    compatible: ['ti,da850-lcdk', 'ti,da850']

  docker:

  imx53-qsrb:
    <<: *arm-device
    boot_method: barebox
    mach: imx
    dtb: dtbs/imx53-qsrb.dtb
    compatible: ['fsl,imx53-qsrb', 'fsl,imx53']

  imx6dl-udoo:
    <<: *arm-device
    mach: imx
    dtb: dtbs/imx6dl-udoo.dtb
    compatible: ['udoo,imx6dl-udoo', 'fsl,imx6dl']

  imx6dl-riotboard:
    <<: *arm-device
    boot_method: barebox
    mach: imx
    dtb: dtbs/imx6dl-riotboard.dtb
    compatible: ['riot,imx6s-riotboard', 'fsl,imx6dl']

  imx6q-sabrelite:
    <<: *arm-device
    mach: imx
    dtb: dtbs/imx6q-sabrelite.dtb
    compatible: ['fsl,imx6q-sabrelite', 'fsl,imx6q']

  imx6q-udoo:
    <<: *arm-device
    mach: imx
    dtb: dtbs/imx6q-udoo.dtb
    compatible: ['udoo,imx6q-udoo', 'fsl,imx6q']

  imx8mm-innocomm-wb15-evk:
    <<: *arm64-device
    boot_method: barebox
    mach: imx
    dtb: dtbs/freescale/imx8mm-innocomm-wb15-evk.dtb
    compatible: ['innocomm,wb15-evk', 'fsl,imx8mm']

  imx8mp-evk:
    <<: *arm64-device
    mach: imx
    dtb: dtbs/freescale/imx8mp-evk.dtb
    compatible: ["fsl,imx8mp-evk", "fsl,imx8mp"]

  imx8mp-tqma8mpql-mba8mpxl:
    <<: *arm64-device
    boot_method: barebox
    mach: imx
    dtb: dtbs/freescale/imx8mp-tqma8mpql-mba8mpxl.dtb
    compatible: ['tq,imx8mp-tqma8mpql-mba8mpxl', 'tq,imx8mp-tqma8mpql', 'fsl,imx8mp']

  imx8mp-verdin-nonwifi-dahlia:
    <<: *arm64-device
    mach: imx
    dtb: dtbs/freescale/imx8mp-verdin-nonwifi-dahlia.dtb
    compatible: ['toradex,verdin-imx8mp-nonwifi-dahlia',
                 'toradex,verdin-imx8mp-nonwifi',
                 'toradex,verdin-imx8mp',
                 'fsl,imx8mp']

  jetson-tk1:
    <<: *arm-device
    mach: nvidia
    dtb: dtbs/nvidia/tegra124-jetson-tk1.dtb
    compatible: ['nvidia,jetson-tk1', 'nvidia,tegra124']

  jh7100-starfive-visionfive-v1:
    <<: *riscv-device
    mach: starfive
    dtb: dtbs/starfive/jh7100-starfive-visionfive-v1.dtb
    compatible: ["starfive,visionfive-v1", "starfive,jh7100"]

  jh7110-starfive-visionfive-2-v1-3b:
    <<: *riscv-device
    mach: starfive
    dtb: dtbs/starfive/jh7110-starfive-visionfive-2-v1.3b.dtb
    compatible: ["starfive,visionfive-2-v1.3b", "starfive,jh7110"]

  juno-uboot:
    <<: *arm64-device
    mach: vexpress
    dtb: dtbs/arm/juno.dtb
    compatible: ['arm,juno', 'arm,vexpress']

  k3-am625-verdin-wifi-mallow:
    <<: *arm64-device
    mach: ti
    dtb: dtbs/ti/k3-am625-verdin-wifi-mallow.dtb
    compatible: ['toradex,verdin-am62-wifi-mallow', 'toradex,verdin-am62-wifi',
                 'toradex,verdin-am62', 'ti,am625']

  k3-j721e-sk:
    <<: *arm64-device
    mach: ti
    dtb: dtbs/ti/k3-j721e-sk.dtb
    compatible: ['ti,j721e-sk', 'ti,j721e']

  k3-j721e-beagleboneai64:
    <<: *arm64-device
    mach: ti
    dtb: dtbs/ti/k3-j721e-beagleboneai64.dtb
    compatible: ['beagle,j721e-beagleboneai64', 'ti,j721e']

  kontron-bl-imx8mm:
    <<: *arm64-device
    mach: imx
    dtb: dtbs/freescale/imx8mm-kontron-bl.dtb
    compatible: ['kontron,imx8mm-bl', 'kontron,imx8mm-sl', 'fsl,imx8mm']

  kontron-kbox-a-230-ls:
    <<: *arm64-device
    mach: freescale
    dtb: dtbs/freescale/fsl-ls1028a-kontron-kbox-a-230-ls.dtb
    compatible: ['kontron,kbox-a-230-ls', 'kontron,sl28-var4', 'kontron,sl28', 'fsl,ls1028a']

  kontron-kswitch-d10-mmt-6g-2gs:
    <<: *arm-device
    mach: microchip
    dtb: dtbs/lan966x-kontron-kswitch-d10-mmt-6g-2gs.dtb
    compatible: ['kontron,kswitch-d10-mmt-6g-2gs', 'kontron,s1921', 'microchip,lan9668', 'microchip,lan966']

  kontron-kswitch-d10-mmt-8g:
    <<: *arm-device
    mach: microchip
    dtb: dtbs/lan966x-kontron-kswitch-d10-mmt-8g.dtb
    compatible: ['kontron,kswitch-d10-mmt-8g', 'kontron,s1921', 'microchip,lan9668', 'microchip,lan966']

  kontron-sl28-var3-ads2:
    <<: *arm64-device
    mach: freescale
    dtb: dtbs/freescale/fsl-ls1028a-kontron-sl28-var3-ads2.dtb
    compatible: ['kontron,sl28-var3-ads2', 'kontron,sl28-var3', 'kontron,sl28', 'fsl,ls1028a']

  kubernetes:

  meson-axg-s400:
    <<: *arm64-device
    mach: amlogic
    dtb: dtbs/amlogic/meson-axg-s400.dtb
    compatible: ['amlogic,s400', 'amlogic,a113d', 'amlogic,meson-axg']

  meson-g12a-u200:
    <<: *arm64-device
    mach: amlogic
    dtb: dtbs/amlogic/meson-g12a-u200.dtb
    compatible: ['amlogic,u200', 'amlogic,g12a']

  meson-g12a-x96-max:
    <<: *arm64-device
    mach: amlogic
    dtb: dtbs/amlogic/meson-g12a-x96-max.dtb
    compatible: ['amediatech,x96-max', 'amlogic,g12a']

  meson-g12b-a311d-libretech-cc:
    <<: *arm64-device
    mach: amlogic
    dtb: dtbs/amlogic/meson-g12b-a311d-libretech-cc.dtb
    compatible: ['libretech,aml-a311d-cc', 'amlogic,a311d', 'amlogic,g12b']

  meson-g12b-a311d-khadas-vim3:
    <<: *arm64-device
    mach: amlogic
    dtb: dtbs/amlogic/meson-g12b-a311d-khadas-vim3.dtb
    compatible: ['khadas,vim3', 'amlogic,a311d', 'amlogic,g12b']

  meson-g12b-odroid-n2:
    <<: *arm64-device
    mach: amlogic
    dtb: dtbs/meson-g12b-odroid-n2.dtb
    compatible: ['hardkernel,odroid-n2', 'amlogic,s922x', 'amlogic,g12b']

  meson-gxl-s905d-p230:
    <<: *arm64-device
    mach: amlogic
    dtb: dtbs/meson-gxl-s905d-p230.dtb
    compatible: ['amlogic,p230', 'amlogic,s905d', 'amlogic,meson-gxl']

  meson-gxl-s905x-libretech-cc:
    <<: *arm64-device
    mach: amlogic
    dtb: dtbs/amlogic/meson-gxl-s905x-libretech-cc.dtb
    compatible: ['libretech,aml-s905x-cc', 'amlogic,s905x', 'amlogic,meson-gxl']

  meson-sm1-khadas-vim3l:
    <<: *arm64-device
    mach: amlogic
    dtb: dtbs/amlogic/meson-sm1-khadas-vim3l.dtb
    compatible: ['khadas,vim3l', 'amlogic,sm1']

  meson-sm1-s905d3-libretech-cc:
    <<: *arm64-device
    mach: amlogic
    dtb: dtbs/amlogic/meson-sm1-s905d3-libretech-cc.dtb
    compatible: ['libretech,aml-s905d3-cc', 'amlogic,sm1']

  meson-sm1-sei610:
    <<: *arm64-device
    mach: amlogic
    dtb: dtbs/amlogic/meson-sm1-sei610.dtb
    compatible: ['seirobotics,sei610', 'amlogic,sm1']

  # No job is being scheduled on this board as its infrastructure errors need to be fixed first.
  minnowboard-turbot-E3826: *x86_64-device

  mt7629-rfb:
    <<: *arm-device
    mach: mediatek
    dtb: dtbs/mt7629-rfb.dtb
    compatible: ['mediatek,mt7629-rfb', 'mediatek,mt7629']

  mt8365-genio-350-evk:
    <<: *arm64-device
    mach: mediatek
    dtb: dtbs/mediatek/mt8365-evk.dtb
    compatible: ['mediatek,mt8365-evk', 'mediatek,mt8365']

  mt8390-genio-700-evk:
    <<: *arm64-device
    mach: mediatek
    dtb: dtbs/mediatek/mt8390-genio-700-evk.dtb
    compatible: ['mediatek,mt8390-evk', 'mediatek,mt8390', 'mediatek,mt8188']

  mt8395-genio-1200-evk:
    <<: *arm64-device
    mach: mediatek
    dtb: dtbs/mediatek/mt8395-genio-1200-evk.dtb
    compatible: ['mediatek,mt8395-evk', 'mediatek,mt8395', 'mediatek,mt8195']

  odroid-xu3:
    <<: *arm-device
    mach: samsung
    dtb: dtbs/exynos5422-odroidxu3.dtb
    compatible: ['hardkernel,odroid-xu3', 'samsung,exynos5800', 'samsung,exynos5']

  # TODO: verify why this platform appears in test results
  # probably mistake and its same as qcs6490-rb3gen2
  qcs6490:
    <<: *arm64-device
    boot_method: fastboot
    mach: qcom
    dtb: dtbs/qcom/qcs6490-rb3gen2.dtb
    compatible: ['qcom,qcs6490-rb3gen2', 'qcom,qcm6490']

  qcs6490-rb3gen2:
    <<: *arm64-device
    boot_method: fastboot
    mach: qcom
    dtb: dtbs/qcom/qcs6490-rb3gen2.dtb
    compatible: ['qcom,qcs6490-rb3gen2', 'qcom,qcm6490']

  qcs8300-ride:
    <<: *arm64-device
    boot_method: fastboot
    mach: qcom
    dtb: dtbs/qcom/qcs8300-ride.dtb
    compatible: ['qcom,qcs8300-ride', 'qcom,qcs8300']

  qcs9100-ride:
    <<: *arm64-device
    boot_method: fastboot
    mach: qcom
    dtb: dtbs/qcom/qcs9100-ride.dtb
    compatible: ['qcom,qcs9100-ride', 'qcom,qcs9100']

  qemu: &qemu-device
    base_name: qemu
    arch: x86_64
    boot_method: qemu
    mach: qemu
    context:
      arch: x86_64
      cpu: qemu64
      guestfs_interface: ide

  qemu-x86: *qemu-device

  rk3288-rock2-square:
    <<: *arm-device
    mach: rockchip
    dtb: dtbs/rk3288-rock2-square.dtb
    compatible: ['radxa,rock2-square', 'rockchip,rk3288']

  rk3288-veyron-jaq:
    <<: *arm-device
    boot_method: depthcharge
    mach: rockchip
    dtb: dtbs/rk3288-veyron-jaq.dtb
    compatible: ['google,veyron-jaq-rev5', 'google,veyron-jaq-rev4']

  rk3399-gru-kevin:
    <<: *arm64-device
    boot_method: depthcharge
    mach: rockchip
    dtb: dtbs/rockchip/rk3399-gru-kevin.dtb
    compatible: ['google,kevin-rev15', 'google,kevin-rev14']

  rk3399-khadas-edge-v:
    <<: *arm64-device
    mach: rockchip
    dtb: dtbs/rockchip/rk3399-khadas-edge-v.dtb
    compatible: ['khadas,edge-v', 'rockchip,rk3399']

  rk3399-roc-pc:
    <<: *arm64-device
    mach: rockchip
    dtb: dtbs/rockchip/rk3399-roc-pc.dtb
    compatible: ['firefly,roc-rk3399-pc', 'rockchip,rk3399']

  rk3399-rock-pc:
    <<: *arm64-device
    mach: rockchip
    dtb: dtbs/rockchip/rk3399-roc-pc.dtb
    compatible: ['firefly,roc-rk3399-pc', 'rockchip,rk3399']

  rk3399-rock-pi-4b:
    <<: *arm64-device
    mach: rockchip
    dtb: dtbs/rockchip/rk3399-rock-pi-4b.dtb
    compatible: ['radxa,rockpi4b', 'radxa,rockpi4', 'rockchip,rk3399']

  rk3588-rock-5b:
    <<: *arm64-device
    mach: rockchip
    dtb: dtbs/rockchip/rk3588-rock-5b.dtb
    compatible: ['radxa,rock-5b', 'rockchip,rk3588']

  x1e80100:
    <<: *arm64-device
    boot_method: fastboot
    mach: qcom
    dtb: dtbs/qcom/x1e80100-crd.dtb
    compatible: ['qcom,x1e80100-crd', 'qcom,x1e80100']

  shell:

  stm32mp157a-dhcor-avenger96:
    <<: *arm-device
    mach: st
    dtb: dtbs/stm32mp157a-dhcor-avenger96.dtb
    compatible: ['arrow,stm32mp157a-avenger96', 'dh,stm32mp157a-dhcor-som',
                     'st,stm32mp157']

  stm32mp157c-lxa-tac-gen1:
    <<: *arm-device
    boot_method: barebox
    mach: st
    dtb: dtbs/stm32mp157c-lxa-tac-gen1.dtb
    compatible: ['lxa,stm32mp157c-tac-gen1', 'oct,stm32mp15xx-osd32', 'st,stm32mp157']

  supermicro-as-2015hr-tnr:
    arch: x86_64
    boot_method: grubhd0
    mach: x86

  sun20i-d1-nezha:
    <<: *riscv-device
    mach: allwinner
    dtb: dtbs/allwinner/sun20i-d1-nezha.dtb
    compatible: ["allwinner,d1-nezha", "allwinner,sun20i-d1"]

  sun7i-a20-cubieboard2:
    <<: *arm-device
    mach: allwinner
    dtb: dtbs/sun7i-a20-cubieboard2.dtb
    compatible: ['cubietech,cubieboard2', 'allwinner,sun7i-a20']

  sun8i-a33-olinuxino:
    <<: *arm-device
    mach: allwinner
    dtb: dtbs/sun8i-a33-olinuxino.dtb
    compatible: ['olimex,a33-olinuxino','allwinner,sun8i-a33']

  sun8i-a83t-bananapi-m3:
    <<: *arm-device
    mach: allwinner
    dtb: dtbs/sun8i-a83t-bananapi-m3.dtb
    compatible: ['sinovoip,bpi-m3', 'allwinner,sun8i-a83t']

  sun8i-h2-plus-orangepi-r1:
    <<: *arm-device
    mach: allwinner
    dtb: dtbs/sun8i-h2-plus-orangepi-r1.dtb
    compatible: ['xunlong,orangepi-r1', 'allwinner,sun8i-h2-plus']

  sun8i-h2-plus-orangepi-zero:
    <<: *arm-device
    mach: allwinner
    dtb: dtbs/sun8i-h2-plus-orangepi-zero.dtb
    compatible: ['xunlong,orangepi-zero', 'allwinner,sun8i-h2-plus']

  sun8i-h3-orangepi-pc:
    <<: *arm-device
    mach: allwinner
    dtb: dtbs/sun8i-h3-orangepi-pc.dtb
    compatible: ['xunlong,orangepi-pc-plus', 'allwinner,sun8i-h3']

  sun8i-r40-bananapi-m2-ultra:
    <<: *arm-device
    mach: allwinner
    dtb: dtbs/sun8i-r40-bananapi-m2-ultra.dtb
    compatible: ['sinovoip,bpi-m2-ultra', 'allwinner,sun8i-r40']

  sun9i-a80-cubieboard4:
    <<: *arm-device
    mach: allwinner
    dtb: dtbs/sun9i-a80-cubieboard4.dtb
    compatible: ['cubietech,a80-cubieboard4', 'allwinner,sun9i-a80']

  sun50i-a64-pine64-plus:
    <<: *arm64-device
    mach: allwinner
    dtb: dtbs/allwinner/sun50i-a64-pine64-plus.dtb
    compatible: ['pine64,pine64-plus', 'allwinner,sun50i-a64']

  sun50i-h5-libretech-all-h3-cc:
    <<: *arm64-device
    mach: allwinner
    dtb: dtbs/allwinner/sun50i-h5-libretech-all-h3-cc.dtb
    compatible: ['libretech,all-h3-cc-h5', 'allwinner,sun50i-h5']

  sun50i-a64-bananapi-m64:
    <<: *arm64-device
    mach: allwinner
    dtb: dtbs/allwinner/sun50i-a64-bananapi-m64.dtb
    compatible: ['sinovoip,bananapi-m64', 'allwinner,sun50i-a64']

  sun50i-h6-orangepi-one-plus:
    <<: *arm64-device
    mach: allwinner
    dtb: dtbs/allwinner/sun50i-h6-orangepi-one-plus.dtb
    compatible: ['xunlong,orangepi-one-plus', 'allwinner,sun50i-h6']

  sun50i-h6-orangepi-3:
    <<: *arm64-device
    mach: allwinner
    dtb: dtbs/allwinner/sun50i-h6-orangepi-3.dtb
    compatible: ['xunlong,orangepi-3', 'allwinner,sun50i-h6']

  sun50i-h6-pine-h64:
    <<: *arm64-device
    mach: allwinner
    dtb: dtbs/allwinner/sun50i-h6-pine-h64.dtb
    compatible: ['pine64,pine-h64', 'allwinner,sun50i-h6']

