# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Centralized rootfs definitions.
# Jobs reference these by name via 'rootfs_ref' in their params.
# The scheduler resolves rootfs_ref to actual URL params before
# template rendering.
#
# NOTE: Entries must be sorted alphabetically.

rootfs:

  buildroot-baseline:
    ramdisk: 'http://storage.kernelci.org/images/rootfs/buildroot/buildroot-baseline/20230703.0/{brarch}/rootfs.cpio.gz'

  buildroot-baseline-depthcharge:
    ramdisk: 'http://storage.kernelci.org/images/rootfs/buildroot/buildroot-baseline/20230623.0/{brarch}/rootfs.cpio.gz'

  buildroot-baseline-qemu:
    ramdisk: 'http://storage.kernelci.org/images/rootfs/buildroot/buildroot-baseline/20230421.0/{brarch}/rootfs.cpio.gz'

  bullseye:
    nfsroot: 'http://storage.kernelci.org/images/rootfs/debian/bullseye/20240129.0/{debarch}'

  trixie:
    nfsroot: 'http://storage.kernelci.org/images/rootfs/debian/trixie/20260219.0/{debarch}'

  trixie-blktest:
    rootfs: 'https://storage.kernelci.org/images/rootfs/debian/trixie-blktest/20260219.0/amd64'

  trixie-blktest-nfs:
    nfsroot: 'https://storage.kernelci.org/images/rootfs/debian/trixie-blktest/20260219.0/amd64/'

  trixie-fault-injection:
    nfsroot: 'https://storage.kernelci.org/images/rootfs/debian/trixie-fault-injection/20260219.0/{debarch}/'

  trixie-gst-fluster:
    nfsroot: 'https://storage.kernelci.org/images/rootfs/debian/trixie-gst-fluster/20260219.0/{debarch}/'

  trixie-gst-h26forge:
    nfsroot: 'https://storage.kernelci.org/images/rootfs/debian/trixie-gst-h26forge/20260219.0/{debarch}/'

  trixie-kselftest:
    nfsroot: 'https://storage.kernelci.org/images/rootfs/debian/trixie-kselftest/20260219.0/{debarch}'
    ramdiskroot: 'https://storage.kernelci.org/images/rootfs/debian/trixie-kselftest/20260219.0/{debarch}'

  trixie-kselftest-boot:
    nfsroot: 'http://storage.kernelci.org/images/rootfs/debian/trixie-kselftest/20260219.0/{debarch}'

  trixie-kvm-unit-tests:
    nfsroot: 'https://storage.kernelci.org/images/rootfs/debian/trixie-kvm-unit-tests/20260219.0/{debarch}'

  trixie-ltp:
    nfsroot: 'https://storage.kernelci.org/images/rootfs/debian/trixie-ltp/20260219.0/{debarch}'

  trixie-rt:
    nfsroot: 'https://storage.kernelci.org/images/rootfs/debian/trixie-rt/20260219.0/{debarch}'

  trixie-wifi:
    nfsroot: 'https://storage.kernelci.org/images/rootfs/debian/trixie-wifi/20260219.0/{debarch}/'
