_anchors:

  amd-platforms: &amd-platforms
    - acer-R721T-grunt
    - acer-cp514-3wh-r0qs-guybrush
    - asus-CM1400CXA-dalboz
    - dell-latitude-3445-7520c-skyrim
    - hp-x360-14a-cb0001xx-zork
    - lenovo-TPad-C13-Yoga-zork

  intel-platforms: &intel-platforms
    - acer-cbv514-1h-34uz-brya
    - acer-chromebox-cxi5-brask
    - acer-cp514-2h-1130g7-volteer
    - acer-cp514-2h-1160g7-volteer

  mediatek-platforms: &mediatek-platforms
    - mt8183-kukui-jacuzzi-juniper-sku16
    - mt8195-cherry-tomato-r2

  qualcomm-platforms: &qualcomm-platforms
    - sc7180-trogdor-kingoftown
    - sc7180-trogdor-lazor-limozeen

  build-k8s-all: &build-k8s-all
    event:
      channel: node
      kind: checkout
      state: available
    runtime:
      name: k8s-all

  kbuild-event: &kbuild-event
    channel: node
    kind: kbuild
    state: available

  lava-job-collabora: &lava-job-collabora
    runtime:
      type: lava
      name: lava-collabora

  test-job-arm64-mediatek: &test-job-arm64-mediatek
    <<: *lava-job-collabora
    event:
      <<: *kbuild-event
      name: kbuild-gcc-14-arm64-chromebook
    platforms: *mediatek-platforms

  test-job-arm64-mediatek-media-committers: &test-job-arm64-mediatek-media-committers
    <<: *test-job-arm64-mediatek
    event:
      <<: *kbuild-event
      name: kbuild-gcc-14-arm64-chromebook-media-committers

  test-job-arm64-qualcomm: &test-job-arm64-qualcomm
    <<: *test-job-arm64-mediatek
    platforms: *qualcomm-platforms

  test-job-arm64-qualcomm-media-committers: &test-job-arm64-qualcomm-media-committers
    <<: *test-job-arm64-mediatek-media-committers
    platforms: *qualcomm-platforms

  test-job-x86: &test-job-x86
    <<: *lava-job-collabora
    event: &test-job-x86-event
      <<: *kbuild-event
      name: kbuild-gcc-14-x86

  test-job-x86-amd: &test-job-x86-amd
    <<: *test-job-x86
    platforms: *amd-platforms

  test-job-x86-intel: &test-job-x86-intel
    <<: *test-job-x86
    platforms: *intel-platforms

scheduler:

  - job: baseline-arm64-mediatek-chromebook
    <<: *test-job-arm64-mediatek

  - job: baseline-arm64-qualcomm-chromebook
    <<: *test-job-arm64-qualcomm

  - job: baseline-nfs-arm64-mediatek-chromebook
    <<: *test-job-arm64-mediatek

  - job: baseline-nfs-arm64-qualcomm-chromebook
    <<: *test-job-arm64-qualcomm

  - job: baseline-nfs-x86-amd-chromebook
    <<: *test-job-x86-amd

  - job: baseline-nfs-x86-intel-chromebook
    <<: *test-job-x86-intel

  - job: baseline-x86-amd-chromebook
    <<: *test-job-x86-amd

  - job: baseline-x86-intel-chromebook
    <<: *test-job-x86-intel

  - job: kbuild-gcc-14-arm64-chromebook
    <<: *build-k8s-all

  - job: kselftest-acpi
    <<: *test-job-x86-intel

  - job: kselftest-dt
    <<: *lava-job-collabora
    event:
      <<: *kbuild-event
      name: kbuild-gcc-14-arm64-chromebook
    platforms:
      - mt8183-kukui-jacuzzi-juniper-sku16
      - mt8195-cherry-tomato-r2
      - sc7180-trogdor-kingoftown
      - sc7180-trogdor-lazor-limozeen

  - job: kselftest-devices-exist
    <<: *lava-job-collabora
    event:
      <<: *kbuild-event
      name: kbuild-gcc-14-arm64-chromebook
    platforms:
      - mt8195-cherry-tomato-r2

  - job: kselftest-device-error-logs
    <<: *lava-job-collabora
    event:
      <<: *kbuild-event
      name: kbuild-gcc-14-arm64-chromebook
    platforms: *mediatek-platforms

  - job: kselftest-devices-probe
    <<: *lava-job-collabora
    event:
      <<: *kbuild-event
      name: kbuild-gcc-14-arm64-chromebook
    platforms: *mediatek-platforms

  - job: kselftest-cpufreq
    <<: *test-job-x86-intel

  - job: kselftest-cpufreq
    <<: *test-job-x86-amd

  - job: kselftest-cpufreq
    <<: *test-job-arm64-qualcomm

  - job: kselftest-cpufreq
    <<: *test-job-arm64-mediatek

  - job: kselftest-cpufreq-hibernate
    <<: *test-job-x86-intel

  - job: kselftest-cpufreq-hibernate
    <<: *test-job-x86-amd

  - job: kselftest-cpufreq-hibernate
    <<: *test-job-arm64-qualcomm

  - job: kselftest-cpufreq-hibernate
    <<: *test-job-arm64-mediatek

  - job: kselftest-cpufreq-suspend
    <<: *test-job-x86-intel

  - job: kselftest-cpufreq-suspend
    <<: *test-job-x86-amd

  - job: kselftest-cpufreq-suspend
    <<: *test-job-arm64-qualcomm

  - job: kselftest-cpufreq-suspend
    <<: *test-job-arm64-mediatek

  - job: kselftest-dmabuf-heaps
    <<: *test-job-x86-intel

  - job: kselftest-dmabuf-heaps
    <<: *test-job-x86-amd

  - job: kselftest-dmabuf-heaps
    <<: *test-job-arm64-qualcomm

  - job: kselftest-dmabuf-heaps
    <<: *test-job-arm64-mediatek

  - job: kselftest-exec
    <<: *test-job-x86-intel

  - job: kselftest-exec
    <<: *test-job-x86-amd

  - job: kselftest-exec
    <<: *test-job-arm64-qualcomm

  - job: kselftest-exec
    <<: *test-job-arm64-mediatek

  - job: kselftest-iommu
    <<: *test-job-x86-intel

  - job: kselftest-iommu
    <<: *test-job-x86-amd

  - job: kselftest-iommu
    <<: *test-job-arm64-qualcomm

  - job: kselftest-iommu
    <<: *test-job-arm64-mediatek

  # TODO: Need better hardware coverage
  - job: ltp-crypto
    <<: *test-job-x86
    platforms: *intel-platforms

  # TODO: Need better hardware coverage
  - job: ltp-fcntl-locktests
    <<: *test-job-x86
    platforms: *intel-platforms

  # TODO: Need better hardware coverage
  - job: ltp-ima
    <<: *test-job-x86
    platforms: *intel-platforms

  - job: ltp-ipc
    <<: *test-job-x86
    platforms:
      - acer-cp514-2h-1130g7-volteer

  # TODO: Need better hardware coverage
  - job: ltp-mm
    <<: *test-job-x86
    platforms: *intel-platforms

  # TODO: Need better hardware coverage
  - job: ltp-pty
    <<: *test-job-x86
    platforms: *intel-platforms

  # TODO: Need better hardware coverage
  - job: ltp-timers
    <<: *test-job-x86
    platforms: *intel-platforms

  - job: fluster-debian-av1
    <<: *test-job-arm64-mediatek
    platforms:
      - mt8195-cherry-tomato-r2

  - job: fluster-debian-av1-chromium-10bit
    <<: *test-job-arm64-mediatek
    platforms:
      - mt8195-cherry-tomato-r2

  - job: fluster-debian-h264
    <<: *test-job-arm64-mediatek

  - job: fluster-debian-h264-frext
    <<: *test-job-arm64-mediatek

  - job: fluster-debian-h265
    <<: *test-job-arm64-mediatek
    platforms:
      - mt8195-cherry-tomato-r2

  - job: fluster-debian-vp8
    <<: *test-job-arm64-mediatek
    platforms:
      - mt8195-cherry-tomato-r2

  - job: fluster-debian-vp9
    <<: *test-job-arm64-mediatek
    platforms:
      - mt8195-cherry-tomato-r2

  - job: fluster-debian-h264
    <<: *test-job-arm64-qualcomm

  - job: fluster-debian-h264-frext
    <<: *test-job-arm64-qualcomm

  - job: fluster-debian-h265
    <<: *test-job-arm64-qualcomm

  - job: fluster-debian-vp8
    <<: *test-job-arm64-qualcomm

  - job: fluster-debian-vp9
    <<: *test-job-arm64-qualcomm

  - job: fluster-debian-av1
    <<: *test-job-arm64-mediatek-media-committers
    platforms:
      - mt8195-cherry-tomato-r2

  - job: fluster-debian-av1-chromium-10bit
    <<: *test-job-arm64-mediatek-media-committers
    platforms:
      - mt8195-cherry-tomato-r2

  - job: fluster-debian-h264
    <<: *test-job-arm64-mediatek-media-committers

  - job: fluster-debian-h264-frext
    <<: *test-job-arm64-mediatek-media-committers

  - job: fluster-debian-h265
    <<: *test-job-arm64-mediatek-media-committers
    platforms:
      - mt8195-cherry-tomato-r2

  - job: fluster-debian-vp8
    <<: *test-job-arm64-mediatek-media-committers
    platforms:
      - mt8195-cherry-tomato-r2

  - job: fluster-debian-vp9
    <<: *test-job-arm64-mediatek-media-committers
    platforms:
      - mt8195-cherry-tomato-r2

  - job: fluster-debian-h264
    <<: *test-job-arm64-qualcomm-media-committers

  - job: fluster-debian-h264-frext
    <<: *test-job-arm64-qualcomm-media-committers

  - job: fluster-debian-h265
    <<: *test-job-arm64-qualcomm-media-committers

  - job: fluster-debian-vp8
    <<: *test-job-arm64-qualcomm-media-committers

  - job: fluster-debian-vp9
    <<: *test-job-arm64-qualcomm-media-committers

  - job: watchdog-reset-arm64-mediatek
    <<: *test-job-arm64-mediatek

  - job: watchdog-reset-arm64-qualcomm
    <<: *test-job-arm64-qualcomm

  - job: watchdog-reset-x86-amd
    <<: *test-job-x86-amd

  - job: watchdog-reset-x86-intel
    <<: *test-job-x86-intel

  - job: wifi-basic-arm64-mediatek
    <<: *test-job-arm64-mediatek

  - job: wifi-basic-x86-amd
    <<: *test-job-x86-amd

  - job: wifi-basic-x86-intel
    <<: *test-job-x86-intel
