[DEFAULT]
api_config = "staging.kernelci.org"
storage_config = "staging.kernelci.org"
verbose = true

[trigger]
poll_period = 3600
startup_delay = 3

[tarball]
kdir = "/home/kernelci/data/src/linux"
output = "/home/kernelci/data/output"
storage_config = "staging.kernelci.org"

[runner]
output = "/home/kernelci/data/output"
runtime_config = "k8s-gke-eu-west4"

[notifier]

[send_kcidb]
kcidb_topic_name = "playground_kcidb_new"
kcidb_project_id = "kernelci-production"
origin = "kernelci_api"

[test_report]
smtp_host = "smtp.gmail.com"
smtp_port =  465

[timeout]

[regression_tracker]

["storage:staging.kernelci.org"]
storage_cred = "/home/kernelci/data/ssh/id_rsa_tarball"
