# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2023 Collabora Limited
# Author: Jeny Sadadia <jeny.sadadia@collabora.com>

apiVersion: v1
kind: ConfigMap
metadata:
  name: kernelci-pipeline-config
  namespace: default
data:
  settings: "/home/kernelci/config/kernelci.toml"
