_anchors:
  broonie: &broonie
    architectures:
      - x86_64
      - arm64
      - arm

build_configs:
  broonie-misc:
    <<: *broonie
    tree: broonie-misc
    branch: 'for-kernelci'

  broonie-regmap:
    <<: *broonie
    tree: broonie-regmap
    branch: 'for-next'

  broonie-regmap-fixes:
    <<: *broonie
    tree: broonie-regmap
    branch: 'for-linus'

  broonie-regulator:
    <<: *broonie
    tree: broonie-regulator
    branch: 'for-next'

  broonie-regulator-fixes:
    <<: *broonie
    tree: broonie-regulator
    branch: 'for-linus'

  broonie-sound:
    <<: *broonie
    tree: broonie-sound
    branch: 'for-next'

  broonie-sound-fixes:
    <<: *broonie
    tree: broonie-sound
    branch: 'for-linus'

  broonie-spi:
    <<: *broonie
    tree: broonie-spi
    branch: 'for-next'

  broonie-spi-fixes:
    <<: *broonie
    tree: broonie-spi
    branch: 'for-linus'
