_anchors:
  broonie: &broonie
    architectures:
      - x86_64
      - arm64
      - arm

build_configs:
  broonie-regmap:
    <<: *broonie
    tree: broonie-regmap
    branch: 'for-next'

  broonie-regmap-fixes:
    <<: *broonie
    tree: broonie-regmap
    branch: 'for-linus'
