build_configs:
  chrome-platform: &chrome-platform
    tree: chrome-platform
    branch: 'for-next'
    architectures:
      - x86_64
      - arm64
      - arm

  chrome-platform-firmware:
    <<: *chrome-platform
    branch: 'for-firmware-next'
