build_configs:
  chromiumos: &chromiumos
    tree: chromiumos
    branch: 'master'
    architectures:
      - x86_64
      - arm64
      - arm

  chromiumos-5.4:
    <<: *chromiumos
    branch: 'chromeos-5.4'

  chromiumos-5.10:
    <<: *chromiumos
    branch: 'chromeos-5.10'

  chromiumos-5.15:
    <<: *chromiumos
    branch: 'chromeos-5.15'

  chromiumos-6.1:
    <<: *chromiumos
    branch: 'chromeos-6.1'

  chromiumos-6.6:
    <<: *chromiumos
    branch: 'chromeos-6.6'

  chromiumos-6.12:
    <<: *chromiumos
    branch: 'chromeos-6.12'
