build_configs:
  hyperv-next: &hyperv
    tree: hyperv
    branch: 'hyperv-next'
    architectures:
      - x86_64

  hyperv-fixes:
    <<: *hyperv
    branch: 'hyperv-fixes'

  hyperv-fixes-staging:
    <<: *hyperv
    branch: 'hyperv-fixes-staging'

  hyperv-next-staging:
    <<: *hyperv
    branch: 'hyperv-next-staging'
