build_configs:
  linusw: &linusw
    tree: linusw
    branch: 'master'
    architectures:
      - arm64
      - arm

  linusw_devel:
    <<: *linusw
    branch: 'devel'

  linusw_fixes:
    <<: *linusw
    branch: 'fixes'

  linusw_for-next:
    <<: *linusw
    branch: 'for-next'
