build_configs:
  media-committers_fixes: &media-committers
    tree: media-committers
    branch: 'fixes'
    architectures:
      - x86_64
      - arm64
      - arm

  media-committers_next:
    <<: *media-committers
    branch: 'next'
